version: '3'
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"  # admin
      - "8086:8086"  # http
      - "8090:8090"  # interupt
    network_mode: "host"
  chronograf:
    image: chronograf:latest
    container_name: chronograf
    ports:
      - "8888:8888"
    network_mode: "host"
